In [9]:
import numpy as np

In [10]:
np.random.seed(42)
x = np.random.randint(0, 100, size=(15, 10))

print("Matrix x:\n\n", x)

U, S, VT = np.linalg.svd(x, full_matrices=False)

r = 9

document_embeddings = np.dot(U[:, :r], np.diag(S[:r]))

word_embeddings = np.dot(np.diag(S[:r]), VT[:r, :])

document_embeddings = np.round(document_embeddings, 2)
word_embeddings = np.round(word_embeddings, 2)

print("\n\nDocument Embeddings:\n\n", document_embeddings)
print("\n\nWord Embeddings:\n\n", word_embeddings.T)
print("\n")
print("Shape of Document Embeddings:", document_embeddings.shape)
print("Shape of Word Embeddings:", word_embeddings.T.shape)

Matrix x:

 [[51 92 14 71 60 20 82 86 74 74]
 [87 99 23  2 21 52  1 87 29 37]
 [ 1 63 59 20 32 75 57 21 88 48]
 [90 58 41 91 59 79 14 61 61 46]
 [61 50 54 63  2 50  6 20 72 38]
 [17  3 88 59 13  8 89 52  1 83]
 [91 59 70 43  7 46 34 77 80 35]
 [49  3  1  5 53  3 53 92 62 17]
 [89 43 33 73 61 99 13 94 47 14]
 [71 77 86 61 39 84 79 81 52 23]
 [25 88 59 40 28 14 44 64 88 70]
 [ 8 87  0  7 87 62 10 80  7 34]
 [34 32  4 40 27  6 72 71 11 33]
 [32 47 22 61 87 36 98 43 85 90]
 [34 64 98 46 77  2  0  4 89 13]]


Document Embeddings:

 [[-201.49   35.3   -38.34  -19.77   -8.59   18.24   18.29   22.89   19.29]
 [-147.26  -70.19  -26.35   -5.38  -54.18   -2.28    2.21   10.97   -8.43]
 [-145.09   26.81   38.77  -33.8    -3.94  -36.21   22.54  -44.29   -4.61]
 [-190.2   -43.32   13.14   15.7    39.66    1.77   14.61   24.71   -5.47]
 [-132.83  -19.84   57.46   16.56   -0.53    5.76   29.67   11.23   -2.67]
 [-122.42   87.1    -0.45   64.67   -6.6   -33.02  -25.73   17.98  -19.92]
 [-176.57  -24.33