In [1]:
import numpy as np

In [2]:
def get_more_negative(mat, seen, bland=True):
    res, cur = 0, 0
    for i, num in enumerate(mat[0]):
        if num >= 0 or i == 0 or i in seen:
            continue
        if num < 0 and bland: return i # Bland's Rule
        if num < cur:
            cur = num
            res = i
    return res

In [3]:
import math

def get_pivot_row(mat, j):
    res, cur = 0, math.inf
    for i, num in enumerate(mat[:, j]):
        if i == 0:
            continue
        if num <= 0:
            continue
        if mat[i][0] / num < cur:
            cur = mat[i][0] / num
            res = i
    return res

In [4]:
def count_negative_first_row(mat):
    count = 0
    for i, num in enumerate(mat[0]):
        if i == 0:
            continue
        if num < 0:
            count += 1
    return count

In [5]:
def print_res(mat, maximum):
    base = list()
    for j in range(1, len(mat[0])):
        flag = True
        found = True
        index = -1
        for i in range(len(mat)):
            if mat[i][j] == 0:
                continue
            if mat[i][j] == 1 and flag:
                index = i
                flag = False
            else:
                found = False
        if not flag and found:
            base.append((j, mat[index][0]))

    print(f"\nThe {len(base)} variables in the base are the following:\n")
    for var, val in base:
        print(f"X{var}")
    print()

    vars = set()
    print("The optimal variable assignment is the following:\n")
    for var, val in base:
        print(f"X{var}: {np.round(val, 2)}")
        vars.add(var)
    for num in range(1, len(mat[0])):
        if num not in vars:
            print(f"X{num}: 0")
    print()

    if maximum or mat[0][0] == 0:
        print(f"The optimal value of the function is: {np.round(mat[0][0], 3)}")
    else:
        print(f"The optimal value of the function is: {-np.round(mat[0][0], 3)}")

In [6]:
def print_base(mat):
    base = list()
    for j in range(1, len(mat[0])):
        flag = True
        found = True
        index = -1
        for i in range(len(mat)):
            if mat[i][j] == 0:
                continue
            if mat[i][j] == 1 and flag:
                index = i
                flag = False
            else:
                found = False
        if not flag and found:
            base.append(j)
    print("Base: ", end="")
    for b in base:
        print(f"X{b} ", end="")
    print()

In [7]:
def simplex(mat, verbose=True, maximum=False):
    if len(mat) > len(mat[0]):
        print("\nProblem invalid: too many constrains\n\n")
        return
    if np.linalg.matrix_rank(mat) != len(mat):
        print("\nProblem invalid: constrains not independent\n\n")
        return
    if maximum: mat[0] *= -1

    while True:
        seen = set()
        count = count_negative_first_row(mat)
        if verbose:
            print_base(mat)
        while True:
            col = get_more_negative(mat, seen)
            if col == 0 and len(seen) == 0:
                if verbose:
                    print_res(mat, maximum)
                return

            seen.add(col)
            row = get_pivot_row(mat, col)

            if row == 0 and len(seen) == count:
                if verbose:
                    print("\nProblem invalid: solution is unbounded\n\n")
                return
            if row != 0:
                break

        mat[row, :] /= mat[row][col]
        for i in range(len(mat)):
            if i == row:
                continue
            mat[i, :] -= mat[row, :] * mat[i][col]
        if maximum: mat[0] *= -1
        mat[mat == -0] = 0.0
        print(mat, "\n")
        if maximum: mat[0] *= -1

In [11]:
mat = np.array([ # simple matrix, for testing the algorithm --> minimization problem --> this program assumes min, not max
    [0, -1, -1, 0, 0],
    [24, 6, 4, 1, 0],
    [6, 3, -2, 0, 1]
], dtype="float64")

'''
mat = np.array([
    np.array([0, -0.15, -0.25, 0, 0, 0, 0, 0, 0], dtype="float64"),
    np.array([1, 1, 0, 1, 0, 0, 0, 0, 0], dtype="float64"),
    np.array([1, 0, 1, 0, 1, 0, 0, 0, 0], dtype="float64"),
    np.array([1, 1, 1, 0, 0, 1, 0, 0, 0], dtype="float64"),
    np.array([1/2, 1/3, 1, 0, 0, 0, 1, 0, 0], dtype="float64"),
    np.array([0, -1, 2, 0, 0, 0, 0, 1, 0], dtype="float64"),
    np.array([-1/6, -1, 0, 0, 0, 0, 0, 0, 1], dtype="float64"),
])

# expected: X1 = 0.75, X2 = 0.25, optimal = 0.175

simplex(mat, verbose=True, maximum=True)

'''

'''
mat = np.array([
    np.array([0, 25, 16, 0, 0, 0], dtype="float64"),
    np.array([-4, -1, -7, 1, 0, 0], dtype="float64"),
    np.array([-5, -1, -5, 0, 1, 0], dtype="float64"),
    np.array([-9, -2, -3, 0, 0, 1], dtype="float64")
])
'''
'''
mat = np.array([
    [0, -3, -2, 0, 0, 0],
    [4, 2, 1, 1, 0, 0],
    [2, -2, 1, 0, 1, 0],
    [1, 1, -1, 0, 0, 1]
], dtype="float64")
simplex(mat, verbose=True, maximum=True)
'''

mat = np.array([
    [0, -6, -8, 6, 0, 0],
    [1, -1, -2, -1, 1, 0],
    [1, 3, -4, 3, 0, 1]
], dtype="float64")

mat = np.array([
    [0, 2, 1, 0, 0],
    [4, 1, 1, 1, 0],
    [9, 3, 1, 0, 1]
], dtype="float64")

simplex(mat, verbose=True, maximum=True)

Base: X3 X4 
[[-6.          0.          0.33333333  0.         -0.66666667]
 [ 1.          0.          0.66666667  1.         -0.33333333]
 [ 3.          1.          0.33333333  0.          0.33333333]] 

Base: X1 X3 
[[-6.5  0.   0.  -0.5 -0.5]
 [ 1.5  0.   1.   1.5 -0.5]
 [ 2.5  1.   0.  -0.5  0.5]] 

Base: X1 X2 

The 2 variables in the base are the following:

X1
X2

The optimal variable assignment is the following:

X1: 2.5
X2: 1.5
X3: 0
X4: 0

The optimal value of the function is: 6.5


In [9]:
%timeit simplex(mat, verbose=False)

36.2 µs ± 2.53 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
#Here is a simple implementation of the simplex algorithm --> Slack variables are identified with incremental integers, following those of the regular variables --> I assume at least as many slack variables as constraints --> It does not support Integer Linear Programming (ILP).