In [10]:
import numpy as np
import scipy as sp
from matplotlib import pyplot as plt

In [11]:
M = np.array([[1, 2], [2, 1], [3, 4], [4, 3]])

U, sigma, Vt = sp.linalg.svd(M, full_matrices=False)

print("Shape of M:", M.shape)
print("Shape of U:", U.shape)
print("Shape of Sigma:", sigma.shape)
print("Shape of Vt:", Vt.shape)
print("\nU:\n", U)
print("Sigma:\n", sigma)
print("Vt:\n", Vt)

Shape of M: (4, 2)
Shape of U: (4, 2)
Shape of Sigma: (2,)
Shape of Vt: (2, 2)

U:
 [[-0.27854301  0.5       ]
 [-0.27854301 -0.5       ]
 [-0.64993368  0.5       ]
 [-0.64993368 -0.5       ]]
Sigma:
 [7.61577311 1.41421356]
Vt:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [12]:
MTM = np.dot(M.T, M)
Evals, Evecs = sp.linalg.eigh(MTM)
sorted_indices = np.argsort(Evals)[::-1]
Evals = Evals[sorted_indices]
Evecs = Evecs[:, sorted_indices]

print("Shape of MTM:", MTM.shape)
print("Shape of Evals:", Evals.shape)
print("Shape of Evecs:", Evecs.shape)
print("Eigenvalues (sorted):", Evals)
print("Eigenvectors (sorted):\n", Evecs)

Shape of MTM: (2, 2)
Shape of Evals: (2,)
Shape of Evecs: (2, 2)
Eigenvalues (sorted): [58.  2.]
Eigenvectors (sorted):
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [13]:
V = Vt.T
print("V (transpose of Vt):\n", V)
print("Evecs:\n", Evecs)

V (transpose of Vt):
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Evecs:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [14]:
sigma_squared = sigma**2

err = np.linalg.norm(sigma_squared - Evals, ord=1)

print("L1 norm of the difference between singular values squared and eigenvalues: ", err)

L1 norm of the difference between singular values squared and eigenvalues:  2.1760371282653068e-14
