In [1]:
import numpy as np

In [2]:
(-7 / 2) * np.array([1, 7]) + (11 / 2) * np.array([1, 5])

array([2., 3.])

In [3]:
A = np.array([
    [2, 1, 1, 0, 0],
    [-2, 1, 0, 1, 0],
    [1, -1, 0, 0, 1]
], dtype="float64")
B = np.array([
    [2, 1, 0],
    [-1, 1, 1],
    [1, -1, 0]
], dtype="float64")
b = np.array([4, 2, 1], dtype="float64")
N = np.array([
    [1, 0],
    [0, 1],
    [0, 0]
], dtype="float64")
cb = np.array([-3, -2, 0], dtype="float64")
cn = np.array([0, 0], dtype="float64")
c = np.array([-3, -2, 0, 0, 0], dtype="float64")

In [4]:
np.linalg.inv(B) @ b

array([1.66666667, 0.66666667, 3.        ])

In [5]:
cb @ np.linalg.inv(B) @ b

-6.333333333333333

In [6]:
cn - cb @ np.linalg.inv(B) @ N

array([1.66666667, 0.        ])

In [7]:
cb - cb @ np.linalg.inv(B) @ B

array([ 0.00000000e+00, -2.22044605e-16,  0.00000000e+00])

In [8]:
c - cb @ np.linalg.inv(B) @ A

array([ 0.00000000e+00, -2.22044605e-16,  1.66666667e+00,  0.00000000e+00,
       -3.33333333e-01])

In [9]:
k = np.array([
    [2, -2],
    [1, 1]
], dtype="float64")
v = np.array([3, 2])

np.linalg.inv(k) @ v

array([1.75, 0.25])

# Strong Duality Example

In [24]:
A = np.array([
    [5, 1, 3],
    [3, 1, 0]
])
B = np.array([
    [5, 3],
    [3, 0],
])
b = np.array([8, 3])
c = np.array([13, 10, 6])
c_sol = np.array([13, 6])
B_inv = np.linalg.inv(B)

# optimality check --> reduced cost all non-negative

c - c_sol @ B_inv @ A

array([0., 7., 0.])

In [29]:
B_inv @ b

array([1., 1.])

In [30]:
c_sol @ B_inv @ b

19.0

In [31]:
c_sol @ B_inv # questa è la soluzione del problema duale

array([2., 1.])

In [32]:
# costo della soluzione duale (deve essere uguale al costo del primal --> strong duality)
np.array([8, 3]) @ (c_sol @ B_inv)

19.0

In [3]:
A = np.array([
    [1, 2],
    [2, -1],
    [1, -1]
])
x = np.array([20 / 3, 11 / 3])
b = np.array([14, 10, 3])

A @ x

array([14.        ,  9.66666667,  3.        ])

In [4]:
B = np.array([
    [1, 2, 0],
    [2, -1, 1],
    [1, -1, 0]
])
N = np.array([
    [1, 0],
    [0, 0],
    [0, 1]
])
cb = np.array([-2, -1, 0])
cn = np.array([0, 0])

cn - cb @ np.linalg.inv(B) @ N

array([1., 1.])

In [3]:
np.linalg.inv(B) @ np.array([14, 10, 3])

array([6.66666667, 3.66666667, 0.33333333])

In [1]:
import mip

In [2]:
model = mip.Model()
x1 = model.add_var(name="X", lb=0, var_type=mip.INTEGER)
x2 = model.add_var(name="Y", lb=0, var_type=mip.INTEGER)

model.add_constr(x1 <= 3)
model.add_constr(x2 <= 2)
model.add_constr(2 * x1 + 2 * x2 <= 7)

model.objective = mip.maximize(3 * x1 - x2)

model.optimize()

print(f"\n\nObjective function value: {round(model.objective.x, 2)}")

for var in model.vars:
    print(f"{var.name}  =  {round(var.x, 2)}")

Welcome to the CBC MILP Solver 
Version: Trunk
Build Date: Oct 28 2021 

Starting solution of the Linear programming relaxation problem using Primal Simplex

Coin0506I Presolve 0 (-3) rows, 0 (-2) columns and 0 (-4) elements
Clp0000I Optimal - objective value 9
Coin0511I After Postsolve, objective 9, infeasibilities - dual 0 (0), primal 0 (0)
Clp0032I Optimal objective 9 - 0 iterations time 0.002, Presolve 0.00, Idiot 0.00

Starting MIP optimization


Objective function value: 9.0
X  =  3.0
Y  =  0.0


In [6]:
model = mip.Model()

x1 = model.add_var(name="X1", lb=0, var_type=mip.CONTINUOUS)
x2 = model.add_var(name="X2", lb=0, var_type=mip.CONTINUOUS)
x3 = model.add_var(name="X3", lb=0, var_type=mip.CONTINUOUS)
x4 = model.add_var(name="X4", lb=0, var_type=mip.CONTINUOUS)

model.add_constr(2 * x1 + x2 + 2 * x4>= 8)
model.add_constr(2 * x1 + 3 * x2 >= 12)
model.add_constr(x2 + 2 * x4 >= 1)

model.objective = mip.minimize(4 * x1 + 3 * x2 + 2 * x4)
model.optimize()
model.objective.x

Coin0506I Presolve 3 (0) rows, 3 (-1) columns and 7 (0) elements
Clp1000I sum of infeasibilities 4.1414e-11 - average 1.38047e-11, 0 fixed columns
Coin0506I Presolve 3 (0) rows, 3 (0) columns and 7 (0) elements
Clp0006I 0  Obj 16.000063 Dual inf 900 (3)
Clp0029I End of values pass after 3 iterations
Clp0000I Optimal - objective value 16
Clp0000I Optimal - objective value 16
Clp0000I Optimal - objective value 16
Coin0511I After Postsolve, objective 16, infeasibilities - dual 0 (0), primal 0 (0)
Clp0032I Optimal objective 16 - 0 iterations time 0.002, Presolve 0.00, Idiot 0.00
Starting solution of the Linear programming problem using Primal Simplex



16.0

In [10]:
model = mip.Model()

x1 = model.add_var(name="X1", lb=0, var_type=mip.CONTINUOUS)
x2 = model.add_var(name="X2", lb=0, var_type=mip.CONTINUOUS)

model.add_constr(-4 * x1 + 6 * x2 <= 9)
model.add_constr(x1 + x2 <= 4)
model.add_constr(-3 * x1 + 6 * x2 <= 10)
model.add_constr(x2 >= 2)

model.objective = mip.minimize(x1 - 2 * x2)

model.optimize()

print(round(model.objective.x, 2))

for var in model.vars:
    print(f"{var.name}  =  {round(var.x, 2)}")

Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cgl0015I Clique Strengthening extended 0 cliques, 0 were dominated
Cbc3007W No integer variables
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Starting solution of the Linear programming problem using Primal Simplex

-3.33
X1  =  1.0
X2  =  2.17
