# SVD decomposition with `scipy`

Import the required modules

In [1]:
import scipy.linalg as la
import numpy as np

Generate a random 5x4 matrix

In [2]:
A = np.random.rand(5,4)
A

array([[1.06046348e-01, 5.06484890e-02, 3.38551811e-01, 2.88525147e-01],
       [7.06730485e-01, 5.94977415e-04, 9.88540113e-01, 3.33401060e-01],
       [3.61514816e-01, 3.29512597e-01, 4.71409365e-01, 5.70938289e-01],
       [2.71950157e-01, 5.18775271e-01, 3.68967553e-02, 4.28336111e-01],
       [9.30229229e-01, 3.56163109e-02, 1.85981435e-01, 7.31712025e-01]])

## `<numpy|scipy>.linalg.svd` 

Equivalent implementations:
- https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html



### Full SVD (`full_matrices = True` - default)

**input:**

$A \in \mathbb{R}^{m\times n}$

**output:**

$U \in \mathbb{R}^{m\times m}, S \in \mathbb{R}^{m\times n}, V \in \mathbb{R}^{n\times n}$

or, more precisely

$\boldsymbol{\sigma} \in \mathbb{R}^{q} $

where $q = \min(m,n)$.


In [3]:
U, s, VT = np.linalg.svd(A)
#U, s, VT = la.svd(A)
print('U shape: ', U.shape)
print('s shape: ', s.shape)
print('VT shape: ', VT.shape)

U shape:  (5, 5)
s shape:  (4,)
VT shape:  (4, 4)


Build the matrix $S$

In [4]:
S = np.zeros(A.shape)
for i in range(len(s)):
    S[i, i] = s[i]
S

array([[1.90914707, 0.        , 0.        , 0.        ],
       [0.        , 0.75506992, 0.        , 0.        ],
       [0.        , 0.        , 0.54360171, 0.        ],
       [0.        , 0.        , 0.        , 0.20250587],
       [0.        , 0.        , 0.        , 0.        ]])

In [5]:
S = la.diagsvd(s, A.shape[0], A.shape[1]) # fa la stessa cosa della cella precedente, ma più veloce
S

array([[1.90914707, 0.        , 0.        , 0.        ],
       [0.        , 0.75506992, 0.        , 0.        ],
       [0.        , 0.        , 0.54360171, 0.        ],
       [0.        , 0.        , 0.        , 0.20250587],
       [0.        , 0.        , 0.        , 0.        ]])

Reconstruct the matrix $A$

In [7]:
A_svd = np.matmul(U, np.matmul(S,VT))
print('err: %e' % (la.norm(A - A_svd) / np.linalg.norm(A)))

err: 5.106853e-16


### Thin SVD (`full_matrices = False`)

**input:**

$A \in \mathbb{R}^{m\times n}$

**output:**

$U \in \mathbb{R}^{m\times q}, S \in \mathbb{R}^{q\times q}, V \in \mathbb{R}^{n\times q}$

or, more precisely

$\boldsymbol{\sigma} \in \mathbb{R}^{q} $

where $q = \min(m,n)$.



In [8]:
del U, s, S, VT
U, s, VT = la.svd(A, full_matrices = False) # non cambia nulla nella pratica --> hai semplicemente eliminato le parti inutili
print('U shape: ', U.shape)
print('s shape: ', s.shape)
print('VT shape: ', VT.shape)

U shape:  (5, 4)
s shape:  (4,)
VT shape:  (4, 4)


Build the matrix $S$

In [9]:
S = np.diag(s) # ecco come creare un matrice quadrata con il vettore in input (s) sulla diagonale
S

array([[1.90914707, 0.        , 0.        , 0.        ],
       [0.        , 0.75506992, 0.        , 0.        ],
       [0.        , 0.        , 0.54360171, 0.        ],
       [0.        , 0.        , 0.        , 0.20250587]])

Reconstruct the matrix $A$

In [10]:
A_svd = np.matmul(U, np.matmul(S,VT))
print('err: %e' % (la.norm(A - A_svd) / la.norm(A)))

err: 5.663776e-16


In [ ]:
# anche qui l'errore è semplicemente la machine precision --> il computer non fa i calcoli perfettamente